apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: testkube-flux2-alert
spec:
  providerRef:
    name: testkube-flux2-generic
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'